export const cinemaHallData = [
    {
        time: '12:00',
        price: 1.99,
        seats: [
            { row: 1,  rowMarker: 'A', seat: 1, state: 'free'},
            { row: 1,  rowMarker: 'A', seat: 2, state: 'busy'},
            { row: 1,  rowMarker: 'A', seat: 3, state: 'free'},
            { row: 1,  rowMarker: 'A', seat: 4, state: 'free'},
            { row: 1,  rowMarker: 'A', seat: 5, state: 'free'},
            { row: 1,  rowMarker: 'A', seat: 6, state: 'free'},
            { row: 1,  rowMarker: 'A', seat: 7, state: 'free'},
            { row: 2,  rowMarker: 'B', seat: 1, state: 'free'},
            { row: 2, rowMarker: 'B', seat: 2, state: 'free'},
            { row: 2, rowMarker: 'B', seat: 3, state: 'free'},
            { row: 2, rowMarker: 'B',seat: 4, state: 'busy'},
            { row: 2, rowMarker: 'B',seat: 5, state: 'free'},
            { row: 2, rowMarker: 'B',seat: 6, state: 'free'},
            { row: 2, rowMarker: 'B',seat: 7, state: 'free'},
            { row: 3, rowMarker: 'C',seat: 1, state: 'free'},
            { row: 3, rowMarker: 'C',seat: 2, state: 'free'},
            { row: 3, rowMarker: 'C',seat: 3, state: 'free'},
            { row: 3, rowMarker: 'C',seat: 4, state: 'free'},
            { row: 3, rowMarker: 'C',seat: 5, state: 'free'},
            { row: 3, rowMarker: 'C',seat: 6, state: 'free'},
            { row: 3, rowMarker: 'C',seat: 7, state: 'free'},
            { row: 4, rowMarker: 'D',seat: 1, state: 'free'},
            { row: 4, rowMarker: 'D',seat: 2, state: 'free'},
            { row: 4, rowMarker: 'D',seat: 3, state: 'busy'},
            { row: 4, rowMarker: 'D',seat: 4, state: 'free'},
            { row: 4, rowMarker: 'D',seat: 5, state: 'free'},
            { row: 4, rowMarker: 'D',seat: 6, state: 'free'},
            { row: 4, rowMarker: 'D',seat: 7, state: 'free'},
            { row: 5, rowMarker: 'E',seat: 1, state: 'free'},
            { row: 5, rowMarker: 'E',seat: 2, state: 'free'},
            { row: 5, rowMarker: 'E',seat: 3, state: 'ghost'},
            { row: 5, rowMarker: 'E',seat: 4, state: 'ghost'},
            { row: 5, rowMarker: 'E',seat: 5, state: 'ghost'},
            { row: 5, rowMarker: 'E',seat: 6, state: 'busy'},
            { row: 5, rowMarker: 'E',seat: 7, state: 'free'},
            { row: 6, rowMarker: 'F',seat: 1, state: 'free'},
            { row: 6, rowMarker: 'F',seat: 2, state: 'ghost'},
            { row: 6, rowMarker: 'F',seat: 3, state: 'ghost'},
            { row: 6, rowMarker: 'F',seat: 4, state: 'ghost'},
            { row: 6, rowMarker: 'F',seat: 5, state: 'ghost'},
            { row: 6, rowMarker: 'F',seat: 6, state: 'ghost'},
            { row: 6, rowMarker: 'F',seat: 7, state: 'free'}
        ]
    },
    {
        time: '15:00',
        price: 2.49,
        seats: [
            { row: 1,  rowMarker: 'A', seat: 1, state: 'free'},
            { row: 1,  rowMarker: 'A', seat: 2, state: 'busy'},
            { row: 1,  rowMarker: 'A', seat: 3, state: 'free'},
            { row: 1,  rowMarker: 'A', seat: 4, state: 'free'},
            { row: 1,  rowMarker: 'A', seat: 5, state: 'free'},
            { row: 1,  rowMarker: 'A', seat: 6, state: 'free'},
            { row: 1,  rowMarker: 'A', seat: 7, state: 'free'},
            { row: 2,  rowMarker: 'B', seat: 1, state: 'busy'},
            { row: 2, rowMarker: 'B', seat: 2, state: 'free'},
            { row: 2, rowMarker: 'B', seat: 3, state: 'free'},
            { row: 2, rowMarker: 'B',seat: 4, state: 'busy'},
            { row: 2, rowMarker: 'B',seat: 5, state: 'free'},
            { row: 2, rowMarker: 'B',seat: 6, state: 'free'},
            { row: 2, rowMarker: 'B',seat: 7, state: 'free'},
            { row: 3, rowMarker: 'C',seat: 1, state: 'free'},
            { row: 3, rowMarker: 'C',seat: 2, state: 'free'},
            { row: 3, rowMarker: 'C',seat: 3, state: 'free'},
            { row: 3, rowMarker: 'C',seat: 4, state: 'free'},
            { row: 3, rowMarker: 'C',seat: 5, state: 'free'},
            { row: 3, rowMarker: 'C',seat: 6, state: 'free'},
            { row: 3, rowMarker: 'C',seat: 7, state: 'free'},
            { row: 4, rowMarker: 'D',seat: 1, state: 'free'},
            { row: 4, rowMarker: 'D',seat: 2, state: 'free'},
            { row: 4, rowMarker: 'D',seat: 3, state: 'busy'},
            { row: 4, rowMarker: 'D',seat: 4, state: 'free'},
            { row: 4, rowMarker: 'D',seat: 5, state: 'free'},
            { row: 4, rowMarker: 'D',seat: 6, state: 'free'},
            { row: 4, rowMarker: 'D',seat: 7, state: 'free'},
            { row: 5, rowMarker: 'E',seat: 1, state: 'busy'},
            { row: 5, rowMarker: 'E',seat: 2, state: 'free'},
            { row: 5, rowMarker: 'E',seat: 3, state: 'ghost'},
            { row: 5, rowMarker: 'E',seat: 4, state: 'ghost'},
            { row: 5, rowMarker: 'E',seat: 5, state: 'ghost'},
            { row: 5, rowMarker: 'E',seat: 6, state: 'free'},
            { row: 5, rowMarker: 'E',seat: 7, state: 'free'},
            { row: 6, rowMarker: 'F',seat: 1, state: 'free'},
            { row: 6, rowMarker: 'F',seat: 2, state: 'ghost'},
            { row: 6, rowMarker: 'F',seat: 3, state: 'ghost'},
            { row: 6, rowMarker: 'F',seat: 4, state: 'ghost'},
            { row: 6, rowMarker: 'F',seat: 5, state: 'ghost'},
            { row: 6, rowMarker: 'F',seat: 6, state: 'ghost'},
            { row: 6, rowMarker: 'F',seat: 7, state: 'free'}
        ]
    },
    {
        time: '17:00',
        price: 5.49,
        seats: [
            { row: 1,  rowMarker: 'A', seat: 1, state: 'free'},
            { row: 1,  rowMarker: 'A', seat: 2, state: 'busy'},
            { row: 1,  rowMarker: 'A', seat: 3, state: 'free'},
            { row: 1,  rowMarker: 'A', seat: 4, state: 'free'},
            { row: 1,  rowMarker: 'A', seat: 5, state: 'free'},
            { row: 1,  rowMarker: 'A', seat: 6, state: 'free'},
            { row: 1,  rowMarker: 'A', seat: 7, state: 'free'},
            { row: 2,  rowMarker: 'B', seat: 1, state: 'free'},
            { row: 2, rowMarker: 'B', seat: 2, state: 'free'},
            { row: 2, rowMarker: 'B', seat: 3, state: 'free'},
            { row: 2, rowMarker: 'B',seat: 4, state: 'busy'},
            { row: 2, rowMarker: 'B',seat: 5, state: 'free'},
            { row: 2, rowMarker: 'B',seat: 6, state: 'free'},
            { row: 2, rowMarker: 'B',seat: 7, state: 'free'},
            { row: 3, rowMarker: 'C',seat: 1, state: 'busy'},
            { row: 3, rowMarker: 'C',seat: 2, state: 'free'},
            { row: 3, rowMarker: 'C',seat: 3, state: 'busy'},
            { row: 3, rowMarker: 'C',seat: 4, state: 'free'},
            { row: 3, rowMarker: 'C',seat: 5, state: 'free'},
            { row: 3, rowMarker: 'C',seat: 6, state: 'free'},
            { row: 3, rowMarker: 'C',seat: 7, state: 'free'},
            { row: 4, rowMarker: 'D',seat: 1, state: 'free'},
            { row: 4, rowMarker: 'D',seat: 2, state: 'busy'},
            { row: 4, rowMarker: 'D',seat: 3, state: 'busy'},
            { row: 4, rowMarker: 'D',seat: 4, state: 'free'},
            { row: 4, rowMarker: 'D',seat: 5, state: 'free'},
            { row: 4, rowMarker: 'D',seat: 6, state: 'free'},
            { row: 4, rowMarker: 'D',seat: 7, state: 'busy'},
            { row: 5, rowMarker: 'E',seat: 1, state: 'free'},
            { row: 5, rowMarker: 'E',seat: 2, state: 'free'},
            { row: 5, rowMarker: 'E',seat: 3, state: 'ghost'},
            { row: 5, rowMarker: 'E',seat: 4, state: 'ghost'},
            { row: 5, rowMarker: 'E',seat: 5, state: 'ghost'},
            { row: 5, rowMarker: 'E',seat: 6, state: 'free'},
            { row: 5, rowMarker: 'E',seat: 7, state: 'free'},
            { row: 6, rowMarker: 'F',seat: 1, state: 'free'},
            { row: 6, rowMarker: 'F',seat: 2, state: 'ghost'},
            { row: 6, rowMarker: 'F',seat: 3, state: 'ghost'},
            { row: 6, rowMarker: 'F',seat: 4, state: 'ghost'},
            { row: 6, rowMarker: 'F',seat: 5, state: 'ghost'},
            { row: 6, rowMarker: 'F',seat: 6, state: 'ghost'},
            { row: 6, rowMarker: 'F',seat: 7, state: 'free'}
        ]
    },
    {
        time: '21:30',
        price: 1.99,
        seats: [
            { row: 1,  rowMarker: 'A', seat: 1, state: 'free'},
            { row: 1,  rowMarker: 'A', seat: 2, state: 'busy'},
            { row: 1,  rowMarker: 'A', seat: 3, state: 'busy'},
            { row: 1,  rowMarker: 'A', seat: 4, state: 'busy'},
            { row: 1,  rowMarker: 'A', seat: 5, state: 'free'},
            { row: 1,  rowMarker: 'A', seat: 6, state: 'busy'},
            { row: 1,  rowMarker: 'A', seat: 7, state: 'free'},
            { row: 2,  rowMarker: 'B', seat: 1, state: 'free'},
            { row: 2, rowMarker: 'B', seat: 2, state: 'free'},
            { row: 2, rowMarker: 'B', seat: 3, state: 'busy'},
            { row: 2, rowMarker: 'B',seat: 4, state: 'busy'},
            { row: 2, rowMarker: 'B',seat: 5, state: 'busy'},
            { row: 2, rowMarker: 'B',seat: 6, state: 'free'},
            { row: 2, rowMarker: 'B',seat: 7, state: 'free'},
            { row: 3, rowMarker: 'C',seat: 1, state: 'busy'},
            { row: 3, rowMarker: 'C',seat: 2, state: 'busy'},
            { row: 3, rowMarker: 'C',seat: 3, state: 'free'},
            { row: 3, rowMarker: 'C',seat: 4, state: 'busy'},
            { row: 3, rowMarker: 'C',seat: 5, state: 'free'},
            { row: 3, rowMarker: 'C',seat: 6, state: 'free'},
            { row: 3, rowMarker: 'C',seat: 7, state: 'busy'},
            { row: 4, rowMarker: 'D',seat: 1, state: 'busy'},
            { row: 4, rowMarker: 'D',seat: 2, state: 'busy'},
            { row: 4, rowMarker: 'D',seat: 3, state: 'free'},
            { row: 4, rowMarker: 'D',seat: 4, state: 'free'},
            { row: 4, rowMarker: 'D',seat: 5, state: 'free'},
            { row: 4, rowMarker: 'D',seat: 6, state: 'free'},
            { row: 4, rowMarker: 'D',seat: 7, state: 'free'},
            { row: 5, rowMarker: 'E',seat: 1, state: 'free'},
            { row: 5, rowMarker: 'E',seat: 2, state: 'free'},
            { row: 5, rowMarker: 'E',seat: 3, state: 'ghost'},
            { row: 5, rowMarker: 'E',seat: 4, state: 'ghost'},
            { row: 5, rowMarker: 'E',seat: 5, state: 'ghost'},
            { row: 5, rowMarker: 'E',seat: 6, state: 'free'},
            { row: 5, rowMarker: 'E',seat: 7, state: 'free'},
            { row: 6, rowMarker: 'F',seat: 1, state: 'busy'},
            { row: 6, rowMarker: 'F',seat: 2, state: 'ghost'},
            { row: 6, rowMarker: 'F',seat: 3, state: 'ghost'},
            { row: 6, rowMarker: 'F',seat: 4, state: 'ghost'},
            { row: 6, rowMarker: 'F',seat: 5, state: 'ghost'},
            { row: 6, rowMarker: 'F',seat: 6, state: 'ghost'},
            { row: 6, rowMarker: 'F',seat: 7, state: 'free'}
        ]
    }
]